shell /usr/bin/fish
font_size 12
font_weight 500
font_family JetBrainsMono Nerd Font
background_opacity 0.85
background_blur 8
cursor_trail 8
# Increase delay to reduce CPU/GPU usage
repaint_delay 10
input_delay 3
# Use sync_to_monitor if tearing occurs, but it might add load
sync_to_monitor no
